<?php

declare(strict_types=1);

namespace Chiron\Pipeline\Event;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Server\MiddlewareInterface;

/**
 * AfterMiddlewareEvent is raised after the middleware was executed.
 */
final class AfterMiddlewareEvent
{
    /** @var MiddlewareInterface */
    private MiddlewareInterface $middleware;
    /** @var ResponseInterface|null */
    private ?ResponseInterface $response;

    /**
     * @param MiddlewareInterface $middleware Middleware that was executed.
     * @param ResponseInterface|null $response Response generated by the middleware or null in case there was an error.
     */
    public function __construct(MiddlewareInterface $middleware, ?ResponseInterface $response)
    {
        $this->middleware = $middleware;
        $this->response = $response;
    }

    /**
     * @return MiddlewareInterface
     */
    public function getMiddleware(): MiddlewareInterface
    {
        return $this->middleware;
    }

    /**
     * @return ResponseInterface|null
     */
    public function getResponse(): ?ResponseInterface
    {
        return $this->response;
    }
}
